<?php

namespace Bundle\CalendarBundle\Model;

abstract class Recurrence
{
    protected $id;

    protected $event;

    /**
     * An array of strings representing the days of the week on which this
     * recurrence occurs. Possible integer values are sunday, monday, tuesday,
     * wednesday, thursday, friday and saturday. If you set $days, you must also
     * set $dayFrequency. For example, if $days is 1 and $dayFrequency is 0,
     * then the recurrence is every Monday.
     *
     * @return array
     */
    protected $days;

    /**
     * An array of integers used in combination with $days to specify which week
     * within a month or year this recurrence occurs. For example, if $frequency
     * is monthly, $days is 0 and $dayFrequency contains 2, then the recurrence
     * will occur the second Monday of every month.
     *
     * @var array
     */
    protected $dayFrequency;

    /**
     * An array of numbers, with integer values ranging from 1 to 12, that
     * indicate the months within a year that this recurrence occurs.
     *
     * @var array
     */
    protected $months;

    /**
     * An array of numbers, with integer values ranging from 1 to 31 or -31 to
     * -1, that indicate the days within a month that this recurrence occurs.
     * Negative values indicate the number of days from the last day of the month.
     *
     * @var array
     */
    protected $monthDays;

    /**
     * An array of integer numbers used to specify specific days within an
     * expanded set of occurrences. The numbers specify the index of an expanded
     * sequence of occurrences starting with 1. For example, if $frequency is
     * daily, the event starts on a Monday, and bysetpos is (1, 8), then the
     * recurrence will occur on the first and second Mondays only. If
     * $setPosition is (2, 8) the event or task will occur on the first Tuesday
     * in the sequence and the second Monday.
     *
     * @var array
     */
    protected $setPosition;

    /**
     * An array of numbers, with integer values ranging from 1 to 53 or -53 to -1,
     * that indicate the weeks within a year that this recurrence occurs.
     * Negative values indicate the number of weeks from the last week of the year.
     *
     * @var array
     */
    protected $weekNumber;

    /**
     * An array of numbers, with integer values ranging from 1 to 366 or -366
     * to -1, that indicate the days within a year that this recurrence occurs.
     * Negative values indicate the number of days from the last day of the year.
     *
     * @var array
     */
    protected $yearDay;

    /**
     * The number of occurrences generated by this recurrence.
     *
     * @var int
     */
    protected $count;

    /**
     * The frequency of this recurrence specified by a constant. Possible values
     * are daily, weekly, monthly, or yearly.
     *
     * @var string
     */
    protected $frequency;

    /**
     * A positive integer indicating how often the specified frequency repeats.
     * For example, if $frequency is daily, then an interval value of 2
     * indicates a recurrence every two days.
     *
     * @var int
     */
    protected $interval;

    /**
     * The end date of this recurrence.
     *
     * @var DateTime
     */
    protected $until;

    /**
     * A string that indicates the start day of the week. Possible values are
     * sunday, monday, tuesday, wednesday, thursday, friday, and saturday.
     *
     * @var int
     */
    protected $weekStartDay;
}