rizza_calendar_list:
  pattern:  /
  defaults: { _controller: RizzaCalendarBundle:Calendar:list }

rizza_calendar_listEvents:
  pattern:  /{id}/events
  defaults: { _controller: RizzaCalendarBundle:Calendar:listEvents }

rizza_calendar_show:
  pattern:  /show/{id}
  defaults: { _controller: RizzaCalendarBundle:Calendar:show }

rizza_calendar_add:
  pattern:  /add
  defaults: { _controller: RizzaCalendarBundle:Calendar:add }

rizza_calendar_edit:
  pattern:  /edit/{id}
  defaults: { _controller: RizzaCalendarBundle:Calendar:edit }

rizza_calendar_delete:
  pattern:  /delete/{id}
  defaults: { _controller: RizzaCalendarBundle:Calendar:delete }